services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - SERVER_PORT=8080
    volumes:
      - .:/app
    restart: unless-stopped